window.MathJax = {
  TeX: {
    Macros: {
      Ai:  "{\\text{Ai}}",
      Ad:  "{\\text{Ad}}",
      Bi:  "{\\text{Bi}}",
      bra: ["{\\langle #1 |}", 1],
      ket: ["{| #1 \\rangle}", 1],
      braket: ["{\\langle #1 \\rangle}", 1],
      hg: ["{}_{#1}{#2}_{#3}", 3],
      fg: "{\\mathfrak{g}}",
      fgl: "{\\mathfrak{gl}}",
      fh: "{\\mathfrak{h}}",
      fsl: "{\\mathfrak{sl}}",
      fsu: "{\\mathfrak{su}}",
      fso: "{\\mathfrak{so}}",
      fsp: "{\\mathfrak{sp}}",
      mse: "{\\mathscr E}",
      msp: "{\\mathscr P}",
      mss: "{\\mathscr S}",
      mcb: "{\\mathcal B}",
      mce: "{\\mathcal E}",
      mcf: "{\\mathcal F}",
      mci: "{\\mathcal I}",
      mcs: "{\\mathcal S}",
      mct: "{\\mathcal T}",
      mcu: "{\\mathcal U}",
      m:    "{|}",
      intg: "{\\mathbb Z}",
      cplx: "{\\mathbb C}",
      rtnl: "{\\mathbb Q}",
      prob: "{\\mathbb P}",
      expe: "{\\mathbb E}",
      real: "{\\mathbb R}",
      pint: "{\\mathbb N}",
      span: "{\\text{span}}",
      diag: "{\\text{diag}}",
      dim: "{\\text{dim}}",
      sh: "{\\text{sh}}",
      sgn: "{\\text{sgn}}",
      Tr: "{\\text{Tr}}",
      ty: "{\\text{ty}}",
      deg: "{\\text{deg}}",
      ind: "{\\mathbb I}",
      var: "{\\text{Var}}",
      const: "{\\text{Const}}"
    }
  }
};
